web:
  upload-path: C:\Users\Ahang\Desktop\upload

spring:
  servlet:
    multipart:
      # -1?????
      max-file-size: -1
      max-request-size: -1
  web:
    resources:
      static-locations: classpath:/static/, file:${web.upload-path}/

#minio配置文件
minio:
  endpoint: http://106.14.246.27:9000
  accessKey: admin
  secretKey: 12345678