server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ahang?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sunyuhang233