server:
  port: 9000
spring:
  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/ahang?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sunyuhang233
## mybatis 配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml # 扫描mybatis的实现dao接口*.xml文件
  type-aliases-package: top.hang.data.entity #实体类取别名
  configuration:
    ## 下划线转驼峰配置
    map-underscore-to-camel-case: true
## 显示dao 执⾏sql语句
logging:
  level:
    com.ppl.springboot.dao: debug # 改成你的dao接口文件所在包路径可以打印出sql语句

