server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ahang?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: sunyuhang233
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
